#!/bin/bash

if [ $# -ne 0 ]; then
    dotnet run $@
    exit 0
fi

myPrompt="(tasks-cli) "

while :
do
    echo -n "$myPrompt "
    read -r line
    line=${line,,}
    if [[ $? -eq 1 || "$line" == "q" || "$line" == "quit" ]]; then
        echo
        exit 0
    fi
    if [[ -n "$line" ]]; then
        dotnet run $line
    fi
done
