#!/bin/bash

scriptDir="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"

if [ $# -ne 0 ]; then
    dotnet exec $scriptDir/bin/Debug/net10.0/Tasks-Cli.dll $@
    exit 0
fi

myPrompt="(tasks-cli) "

while :
do
    echo -n "$myPrompt "
    read -r line
    code=$?
    line=${line,,}
    if [[ $code -eq 1 || "$line" == "q" || "$line" == "quit" ]]; then
        echo
        exit 0
    fi
    if [[ -n "$line" ]]; then
    dotnet exec $scriptDir/bin/Debug/net10.0/Tasks-Cli.dll $line
    fi
done
